# Do not modify this file!  It was generated by ‘nixos-generate-config’
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8316714b-ef16-4ce1-9787-4ba2150cc66c";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8316714b-ef16-4ce1-9787-4ba2150cc66c";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8316714b-ef16-4ce1-9787-4ba2150cc66c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/usr" =
    { device = "/dev/disk/by-uuid/8316714b-ef16-4ce1-9787-4ba2150cc66c";
      fsType = "btrfs";
      options = [ "subvol=usr" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8316714b-ef16-4ce1-9787-4ba2150cc66c";
      fsType = "btrfs";
      options = [ "subvol=boot" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/8316714b-ef16-4ce1-9787-4ba2150cc66c";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  swapDevices = [ ];
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
